/*
 * @TODO this have to be generated by the php engine
 */
define([], function () {
    'use strict';

    return {
        core: {
            ApplicationManager: {
                appPath: 'resources/toolbar/src/tb/apps',

                /*ne charge que les onglets qui se trouvent dans 'applications'*/
                active: 'main',

                route: '', // to change: App should know

                applications: {
                    main: {
                        label: 'Main',
                        config: {mainRoute: 'appMain/index'}
                    },
                    layout: {
                        label: 'Layout',
                        config: {mainRoute: 'appLayout/home'}
                    },
                    content: {
                        label: 'Edition du contenu',
                        config: {}
                    },
                    bundle: {
                        label: 'Bundle',
                        config: {mainRoute: 'bundle/index'}
                    },
                    page: {
                        label: 'Page',
                        config: {mainRoute: 'page/index'}
                    },
                    contribution: {
                        label: 'Contribution',
                        config: {mainRoute: 'contribution/index'}
                    }
                }
            }
        },

        component: {
            logger: {

            }
        }
    };
});